### PR TITLE
Use npm package name instead of relative path

### PR DESCRIPTION
**Pull request by keqingrong**

### CODE REVIEW

**Comment by benfred** [comment]
Thanks for the PR! 

I realize that using the relative path instead of the npm package name like I was doing is a total hack - but unfortunately this change doesn't work right now =(. 

The problem is that I want the contour_plot code bundled into fmin_vis.js  - and I don't yet have rollup configured properly to handle this .

So generating the bundle right now with your change gives this error:

```bash
$ npm test

> fmin@0.0.3 pretest /Users/ben/code/fmin
> rm -rf build && mkdir build && json2module package.json > build/package.js && rollup -f umd -n fmin -o build/fmin.js -- index.js && rollup -f umd -n fmin_vis -o build/fmin_vis.js -- index_vis.js

Treating 'contour_plot' as external dependency
No name was provided for external module 'contour_plot' in options.globals – guessing 'contour_plot'
```

And then the examples won't load:

screen shot 2018-06-01 at 10 41 52 am

It should be pretty straightforward to configure rollup to bundle these things - (guide here https://code.lengstorf.com/learn-rollup-js/#add-a-node-module-as-a-dependency). If you want to update the rollup config to handle this that would be awesome!

**Comment by keqingrong** [comment]
Thank you for your reply!

I have updated the rollup config and which should correct the build error.

**Comment by benfred** [comment]
awesome! Thanks for doing this,

**Comment by yebingo** [comment]
> Thank you for your reply!
> 
> I have updated the rollup config and which should correct the build error.

I got this problem too, can you say how to fix this problem? thanks.

**Pull request merged**
